### ISSUE TITLE
The idea of how to increase the speed

### ISSUE THREAD

**Issue by phrutis** [Etayson/BSGS-cuda#13]
Hi Etayson!
I already proposed to implement this idea for [KeyHunt](https://github.com/albertobsd/keyhunt/issues/149)  maybe you can implement it.

There is an idea how to speed up the search for a given range in BSGS-cuda.
Example range puzzle120: 
-pk 800000000000000000000000000000 -pke ffffffffffffffffffffffffffffff
In a sequential search, you will often find 4,5,6,7,8... of the same characters in succession.
I studied almost all private keys on which there were coins, none of which has 4 or more symbols in succession.

As in the English language, not words in which 3,4,5... identical letters go in succession.

An example of identical symbols:
800000007777000000000000000001 ->
800000007777ffffffffffffffffff
range after 7777 invalid

800000eeee00000000000000000001 ->
800000eeeeffffffffffffffffffff
range after eeee invalid

If we assume that here the last **e** is equal to the month of the search
Then it turns out this month wasted.
If you skiped all the same symbols, the speed will increase symmetrically.

Other examples:
FFFF **FFFF FFFF FFFF FFFF FFFF FFFF FFFE BAAE DCE6 AF48 A03B BFD2 5E8C D036 4141** 
all keys after FFFF are invalid.
7777 **FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF**
all keys after 7777 are invalid.
1234 1111 **FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF**
all keys after 1111 are invalid.

1234 5181 1ABC AE0F F5ED 07E1 9BA5 56F3 DAE4 DAEC E5AA AA**FF FFFF FFFF FFFF FFFF** 
all keys after AAAA are invalid.

I know that an additional search for identical characters (prefixes 1111, 2222,... ffff, 11111,33333,aaaaa,fffff.....) may reduce the speed by ~ 5-10%
The total travel time will be less by -30-50%.

You can output the range 1- ffffffff to a file and see how many times 3,4,5,... characters were dropped in a row.
If you increase the range, the same ones will drop out symmetrically more often + intermediate ones. BitCoinCore randomizes private keys, there are almost no identical symbols in a row in random.

What I suggest:
As I understand it, the algorithm creates 3 files from the hex hashes for the private key. If you remove all invalid values ​​from the files, which have 4 or more identical characters.
It will take less RAM memory and also reduce the time it takes to pass the specified range. Which essentially increases the speed.

If with 3 files it is not possible to do this.
You can skip these characters in private.
Instead of further generating the privat key, it is simply skipped. Skipping occurs much faster than generation, so the speed on the counter will increase.

Zeros can be omitted.
If you skip them, then you can search for puzzles like this
800010001000100010001000100010

It is interesting to hear your opinion

**Comment by phrutis** [comment]
If what I suggested is very difficult to implement. 
Make random within the given range.
Something like this, if there is one thread, every second a part of the private key + fast values is generated.
Presumably CUDA has a lot of 65536 threads. 
You can set to generate random every 10-15 minutes.
Random in its essence does not produce 4,5,6,7 identical in succession. 
This will increase your chance of finding faster.

**Comment by Etayson** [comment]
Hi,
in my opinion this can be done without rewriting the program. You can simply divide the range into sub-ranges and filter out those that you think are not possible. And use in the program only those subranges that have passed your filter.
but I cannot add such a filter to the program, because in one case it seems impossible for the private key to contain multiple repeated symbols, but in another case it is quite probable. And the program should find any.

**Comment by phrutis** [comment]
I don’t know the PureBasic programming language, I’m unlikely to do it, I will try.

What do you think about randomness? He will not miss and das are more likely to find faster.
